name: Auto Add Email Forwarding
on:
  pull_request:
    types: [closed]
    branches: [main]
jobs:
  process-email:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR changes
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Find new JSON files
        id: find-json
        run: |
          echo "json_files=$(find registrations/ -name '*.json')" >> $GITHUB_OUTPUT
      - name: Validate and process registrations
        if: steps.find-json.outputs.json_files != ''
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        run: |
          declare -A user_email_count  # 用户邮箱计数器
          failed_checks=0
          for file in ${{ steps.find-json.outputs.json_files }}; do
            echo "Processing $file"
            prefix=$(basename "$file" .json)
            email=$(jq -r '.email' "$file")
            if [[ ! "$prefix" =~ ^[a-z0-9-]{1,20}$ ]]; then
              echo "❌ 错误: 前缀 '$prefix' 只能包含小写字母、数字和短横线，且长度1-20字符"
              ((failed_checks++))
              continue
            fi
            if [[ ! "$email" =~ ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$ ]]; then
              echo "❌ 错误: '$email' 不是有效的邮箱地址"
              ((failed_checks++))
              continue
            fi
            if [ -f "$file" ]; then
              existing_email=$(jq -r '.email' "$file")
              if [ "$existing_email" == "$email" ]; then
                echo "⚠️ 警告: 前缀 '$prefix' 已注册过相同邮箱，跳过"
                continue
              else
                echo "❌ 错误: 前缀 '$prefix' 已被其他邮箱占用"
                ((failed_checks++))
                continue
              fi
            fi
            user_email_count["$email"]=$((user_email_count["$email"] + 1))
            if [ ${user_email_count["$email"]} -gt 3 ]; then
              echo "❌ 错误: 邮箱 '$email' 已注册超过3个前缀"
              ((failed_checks++))
              continue
            fi
            echo "✅ 通过验证: $prefix@yourdomain.com → $email"
            response=$(curl -s -X POST \
              "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/email/routing/rules" \
              -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
              -H "Content-Type: application/json" \
              --data '{
                "matchers": [{
                  "type": "literal",
                  "field": "to",
                  "value": "'"$prefix"'@yourdomain.com"
                }],
                "actions": [{
                  "type": "forward",
                  "value": ["'"$email"'"]
                }]
              }')
            if [[ $(echo "$response" | jq -r '.success') != "true" ]]; then
              echo "❌ Cloudflare API错误: $(echo "$response" | jq -r '.errors[0].message')"
              ((failed_checks++))
            else
              echo "🎉 成功添加: $prefix@yourdomain.com → $email"
            fi
          done
          if [ $failed_checks -ne 0 ]; then
            echo "::error::发现 $failed_checks 个错误，请检查PR内容"
            exit 1
          fi

