name: Auto Add Email Forwarding
on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  process-email:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR changes
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Find new JSON files
        id: find-json
        run: |
          echo "json_files=$(find registrations/ -name '*.json' -not -path './.github/*')" >> $GITHUB_OUTPUT

      - name: Parse JSON and add to Cloudflare
        if: steps.find-json.outputs.json_files != ''
        run: |
          for file in ${{ steps.find-json.outputs.json_files }}; do
            prefix=$(basename "$file" .json)
            email=$(jq -r '.email' "$file")
            
            curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/email/routing/rules" \
              -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
              -H "Content-Type: application/json" \
              --data '{
                "matchers": [
                  {
                    "type": "literal",
                    "field": "to",
                    "value": "'"$prefix"'@qxz.qzz.io"
                  }
                ],
                "actions": [
                  {
                    "type": "forward",
                    "value": ["'"$email"'"]
                  }
                ]
              }'
          done
